{
 "title": "Admin",
 "time": { "from": "2026-01-29T12:53:40.149Z", "to": "2026-01-29T18:53:52.356Z" },
 "templating": {
  "list": [
   {
    "name": "Team",
    "query": "SELECT \n    Team_id as __value,\n    Name as __text\nFROM TEAM;"
   },
   {
    "name": "Car",
    "query": "WITH NumberedCars AS (\n    SELECT \n        c.Car_id,\n        t.Name as TeamName,\n        ROW_NUMBER() OVER (PARTITION BY c.Team_id ORDER BY c.Car_id) as CarNumber\n    FROM CAR c\n    JOIN TEAM t ON c.Team_id = t.Team_id\n    WHERE c.Team_id = ${Team}\n)\nSELECT \n    Car_id as __value,\n    CONCAT('Car ', CarNumber) as __text\nFROM NumberedCars\nORDER BY TeamName, CarNumber;"
   },
   {
    "name": "Simulation",
    "query": "SELECT \n    s.Simulation_id as __value,\n    CONCAT(\n        FORMAT(s.Data_time, 'dd MMM HH:mm:ss'), \n        ' - ', \n        c.Name) as __text\nFROM SIMULATION s\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nORDER BY s.Data_time DESC;"
   },
   {
    "name": "Circuit",
    "query": "SELECT \n    Circuit_id as __value,\n    Name as __text\nFROM CIRCUIT\nORDER BY Name;"
   }
  ]
 },
 "panels": [
  {
   "title": "System Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT\n    (SELECT COUNT(*) FROM [USER])     AS Users,\n    (SELECT COUNT(*) FROM TEAM)       AS Teams,\n    (SELECT COUNT(*) FROM DRIVER)     AS Drivers,\n    (SELECT COUNT(*) FROM SIMULATION) AS Simulations,\n    (SELECT COUNT(*) FROM PART)       AS Parts,\n    (SELECT COUNT(*) FROM SPONSOR)    AS Sponsors;"
    }
   ]
  },
  {
   "title": "Circuit Analysis",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    c.Name as Circuit,\n    c.Total_distance as [Lenght (km)],\n    c.N_Curves as Curves,\n    COUNT(DISTINCT s.Simulation_id) as Simulations,\n    AVG(sp.time_seconds) as [Average Time],\n    MIN(sp.time_seconds) as [Best Time (s)],\n    MAX(sp.time_seconds) as [Worst Time (s)],\n    AVG(sp.v_recta) as [Avg Straight Speed (km/h)],\n    AVG(sp.v_curva) as [Avg Curve Speed (km/h)],\n    AVG(sp.penalty) as [Avg Penalty]\nFROM SIMULATION_PARTICIPANT sp\nJOIN SIMULATION s ON sp.simulation_id = s.Simulation_id\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nWHERE (${Circuit} = 0 OR c.Circuit_id = ${Circuit})\nGROUP BY c.Name, c.Total_distance, c.N_Curves\nORDER BY c.Name;"
    }
   ]
  },
  {
   "title": "Car Setup Evolution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    s.Data_time as time,\n    sp.setup_p as P,\n    sp.setup_a as A,\n    sp.setup_m as M,\n    sp.time_seconds as Time,\n    c.Name as circuit\nFROM SIMULATION_PARTICIPANT sp\nJOIN SIMULATION s ON sp.simulation_id = s.Simulation_id\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nWHERE sp.car_id = ${Car}\nORDER BY s.Data_time;"
    }
   ]
  },
  {
   "title": "Simulation Ranking",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    sp.position AS Ranking,\n    t.Name AS Team,\n    u.Username AS Driver,\n    \n    sp.setup_p AS P,\n    sp.setup_a AS A,\n    sp.setup_m AS M,\n    sp.driver_h AS H,\n    \n    ROUND(sp.time_seconds, 2) AS [Time (s)],\n    ROUND(sp.v_recta, 1) AS [Straight S. (km/h)],\n    ROUND(sp.v_curva, 1) AS [Curve S. (km/h)],\n    ROUND(sp.penalty, 1) AS Penalty\n\nFROM SIMULATION_PARTICIPANT sp\nJOIN SIMULATION s ON sp.simulation_id = s.Simulation_id\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nJOIN TEAM t ON sp.team_id = t.Team_id\nJOIN DRIVER d ON sp.driver_id = d.User_id\nJOIN [USER] u ON d.User_id = u.User_id\nJOIN CAR car ON sp.car_id = car.Car_id\n\nWHERE (${Simulation} = 0 OR s.Simulation_id = ${Simulation})\nORDER BY sp.position;"
    }
   ]
  }
 ]
}