{
 "title": "Engineer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Team",
    "query": "SELECT \n    Team_id as __value,\n    Name as __text\nFROM TEAM;"
   },
   {
    "name": "TeamCar",
    "query": "WITH NumberedCars AS (\n    SELECT \n        c.Car_id,\n        t.Name as TeamName,\n        ROW_NUMBER() OVER (PARTITION BY c.Team_id ORDER BY c.Car_id) as CarNumber\n    FROM CAR c\n    JOIN TEAM t ON c.Team_id = t.Team_id\n    WHERE c.Team_id = ${Team}\n)\nSELECT \n    Car_id as __value,\n    CONCAT(TeamName, ' - Car ', CarNumber) as __text\nFROM NumberedCars\nORDER BY TeamName, CarNumber;"
   },
   {
    "name": "Simulation",
    "query": "SELECT\n    s.Simulation_id AS __value,\n    CONCAT(\n        CONVERT(varchar(19), s.Data_time, 120),\n        ' - ',\n        c.Name\n    ) AS __text\nFROM SIMULATION s\nJOIN CIRCUIT c \n    ON s.Circuit_id = c.Circuit_id\nJOIN SIMULATION_PARTICIPANT sp \n    ON s.Simulation_id = sp.simulation_id\nWHERE sp.team_id = ${Team}\nGROUP BY\n    s.Simulation_id,\n    s.Data_time,\n    c.Name\nORDER BY s.Data_time DESC;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Team Stats",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT\n    COUNT(DISTINCT sp.simulation_id) AS 'Total Races',\n    SUM(CASE WHEN sp.position = 1 THEN 1 ELSE 0 END) AS 'Win',\n    SUM(CASE WHEN sp.position <= 3 THEN 1 ELSE 0 END) AS 'Podiums (Top 3)',\n    ROUND(AVG(sp.position), 2) AS 'Average Position',\n    MIN(sp.position) AS 'Best Position',\n    ROUND(AVG(sp.time_seconds), 2) AS 'Average Time'\nFROM SIMULATION_PARTICIPANT sp\nWHERE sp.team_id = ${Team};"
    }
   ]
  },
  {
   "title": "Car Setups Evolution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    s.Data_time as time,\n    sp.setup_p as P,\n    sp.setup_a as A,\n    sp.setup_m as M,\n    sp.time_seconds as Time,\n    c.Name as circuit\nFROM SIMULATION_PARTICIPANT sp\nJOIN SIMULATION s ON sp.simulation_id = s.Simulation_id\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nWHERE sp.team_id = ${Team}\n  AND sp.car_id = ${TeamCar}\nORDER BY s.Data_time;"
    }
   ]
  },
  {
   "title": "Simulation Details",
   "type": "stat",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    s.Data_time AS time,\n    FORMAT(s.Data_time, 'yyyy-MM-dd') AS race_date,\n    FORMAT(s.Data_time, 'HH:mm')      AS race_time,\n\n    c.Name AS circuit,\n\n    CONCAT(\n        'Car ',\n        DENSE_RANK() OVER (PARTITION BY t.Team_id ORDER BY car.Car_id)\n    ) AS car_number,\n\n    sp.position AS Position,\n    ROUND(sp.time_seconds, 2) AS Time,\n    ROUND(sp.v_recta, 1) AS [Straight Speed],\n    ROUND(sp.v_curva, 1) AS [Curve Speed],\n    ROUND(sp.penalty, 1) AS Penalty,\n    sp.setup_p AS P,\n    sp.setup_a AS A,\n    sp.setup_m AS M,\n    sp.driver_h AS H\n\nFROM SIMULATION_PARTICIPANT sp\nJOIN SIMULATION s ON sp.simulation_id = s.Simulation_id\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nJOIN TEAM t ON sp.team_id = t.Team_id\nJOIN CAR car ON sp.car_id = car.Car_id\nJOIN DRIVER d ON sp.driver_id = d.User_id\nJOIN [USER] u ON d.User_id = u.User_id\n\nWHERE sp.team_id = ${Team}\n  AND (${Simulation} = 0 OR sp.simulation_id = ${Simulation})\n  AND (${TeamCar} = 0 OR sp.car_id = ${TeamCar})\n\nORDER BY s.Data_time DESC, sp.position;"
    }
   ]
  },
  {
   "title": "Average Performance Per Circuit",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    c.Name as Circuit,\n    c.N_Curves as [Number of Curves],\n    AVG(sp.v_recta) as [Average Straight Speed],\n    AVG(sp.v_curva) as [Average Curve Speed],\n    AVG(sp.v_recta - sp.v_curva) as [Speed Difference],\n    COUNT(*) as Races\nFROM SIMULATION_PARTICIPANT sp\nJOIN SIMULATION s ON sp.simulation_id = s.Simulation_id\nJOIN CIRCUIT c ON s.Circuit_id = c.Circuit_id\nWHERE sp.team_id = ${Team}\n  AND (${TeamCar} = 0 OR sp.car_id = ${TeamCar})\nGROUP BY c.Name, c.N_Curves\nORDER BY [Number of Curves];"
    }
   ]
  },
  {
   "title": "Used Partes Summary",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "WITH UsedParts AS (\n    SELECT \n        ssd.category AS Category,\n        p.Name AS Name,\n        AVG(ssd.part_p) AS p,\n        AVG(ssd.part_a) AS a,\n        AVG(ssd.part_m) AS m,\n        AVG(sp.position) AS [Average Position],\n        MIN(sp.position) AS [Best Position]\n    FROM SIMULATION_PARTICIPANT sp\n    JOIN SIMULATION_SETUP_DETAIL ssd \n        ON sp.simulation_id = ssd.simulation_id \n       AND sp.car_id = ssd.car_id\n    JOIN PART p ON ssd.part_id = p.Part_id\n    WHERE sp.team_id = ${Team}\n      AND (${TeamCar} = 0 OR sp.car_id = ${TeamCar})\n    GROUP BY ssd.category, p.Name\n)\nSELECT \n    Category,\n    Name,\n    p,\n    a,\n    m,\n    [Average Position],\n    [Best Position]\nFROM UsedParts;"
    }
   ]
  },
  {
   "title": "Contributions",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "F1GarageManager",
     "rawSql": "SELECT \n    s.Name as Sponsor,\n    s.Industry,\n    s.Country,\n    c.Date,\n    'USD ' + FORMAT(c.Amount, 'N2') as Amount,\n    c.Description\nFROM CONTRIBUTION c\nJOIN SPONSOR s ON c.Sponsor_id = s.Sponsor_id\nJOIN TEAM t ON c.Team_id = t.Team_id\nWHERE t.Team_id = ${Team}\nORDER BY c.Date DESC;"
    }
   ]
  }
 ]
}